apr-util: disable parallel build
Build reliably fails with -j20

    crypto/apr_passwd.c:200:1: fatal error: error closing -: Broken pipe
      200 | }
          | ^
    compilation terminated.

Signed-off-by: Michal Vasilek <michal.vasilek@nic.cz>
(cherry picked from commit bd9e119d68fba792a1f760525540c0e0cf10e63f)