ruby: fix uClibc build
Shamelessly copied from buildroot. All credit goes to Vicente Olivert
Riera.

Currently ruby fails to build on uClibc targets (Arc). The ruby
configure script doesn't detect platform support for finite, isinf and
isnan and defines its own versions, which later clash with uClibc's
implementations.

compiling bigdecimal.c
In file included from ../.././include/ruby/missing.h:23:0,
                 from ../.././include/ruby/defines.h:154,
                 from ../.././include/ruby/ruby.h:29,
                 from bigdecimal.h:14,
                 from bigdecimal.c:13:
bigdecimal.h:97:1: error: static declaration of '__finite' follows non-static declaration
 finite(double)

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>