nvme-cli: update to 2.11
Bump to latest upstream release.

Removed upstreamed: 020-replace_uint16_t
Manually rebased: 010-gcc14.patch

To fix the following build error, added 020-usl-fix-build-due-to-undeclared-locale.patch:

../nvme-print.c: In function 'is_temperature_fahrenheit':
../nvme-print.c:805:19: error: 'LC_MEASUREMENT' undeclared (first use in this function)
  805 |         setlocale(LC_MEASUREMENT, "");
      |                   ^~~~~~~~~~~~~~
../nvme-print.c:805:19: note: each undeclared identifier is reported only once for each function it appears in

Tested the resulting binary and it seems fine:

% nvme smart-log /dev/nvme0 | grep "temperature"
temperature				: 42 °C (315 K)

Build system: x86/64
Build-tested: x86/64
Run-tested: x86/64

Signed-off-by: John Audia <therealgraysky@proton.me>