libftdi1: explicitely disable Boost unit tests
When libftdi1 is detecting the presence of the Boost unit testing framework,
it will conditionally enable the build of libftdi1 test binaries which fail to
link on some targets with the following error:

    CMakeFiles/test_libftdi1.dir/basic.cpp.o: In function `main':
    basic.cpp:(.text.startup+0xc): undefined reference to `boost::unit_test::unit_test_main(bool (*)(), int, char**)'
    collect2: error: ld returned 1 exit status
    test/CMakeFiles/test_libftdi1.dir/build.make:123: recipe for target 'test/test_libftdi1' failed
    make[6]: *** [test/test_libftdi1] Error 1

Since we do not care about test cases and since we want to avoid unpredictable
conditional compilation simply disable the testcases entirely.

Signed-off-by: Jo-Philipp Wich <jo@mein.io>