pen: update to v0.34.0
Update the pen package to upstream release v0.34.0 in order to fix the
following build error reported by the buildbot:

    ssl.o: In function `ssl_create_context':
    ssl.c:(.text+0x9c): undefined reference to `SSLv3_method'
    collect2: error: ld returned 1 exit status

Also switch from PKG_MD5SUM to PKG_HASH with SHA256 while we're at it.

Signed-off-by: Jo-Philipp Wich <jo@mein.io>