frr: enable frr-vtysh by defalult and hide it
Fixes [1]
lib/vty.c: In function 'vty_mgmt_resume_response':
lib/vty.c:195:27: error: 'VTYSH_READ' undeclared (first use in this function); did you mean 'VTY_READ'?
  195 |                 vty_event(VTYSH_READ, vty);
      |                           ^~~~~~~~~~
      |                           VTY_READ

The error is a bug in frr: not all use cases of the VTYSH_* enums are
guarded by #ifdef VTYSH. These enums are enabled by the VTYSH macro,
which is defined if sub package frr-vtysh is enabled in menuconfig.
According to support ticket [2], building without frr-vtysh is
no longer supported.

[1] https://github.com/openwrt/packages/issues/24063
[2] https://github.com/FRRouting/frr/issues/15752#issuecomment-2059328993

Signed-off-by: Georgi Valkov <gvalkov@gmail.com>