rrdtool1: fix compilation with GCC 15
Currently, rrdtool1 produces the following build error
for various C files while building with GCC 15:

In file included from rrd_tool.h:93,
                 from rrd_cgi.c:11:
getopt.h:108:12: error: conflicting types for 'getopt'; have 'int(void)'
  108 | extern int getopt ();
      |            ^~~~~~
In file included from include/fortify/unistd.h:22,
                 from rrd_tool.h:56:
include/unistd.h:127:5: note: previous declaration of 'getopt' with type 'int(int,  char * const*, const char *)'
  127 | int getopt(int, char * const [], const char *);
      |     ^~~~~~

This adds a patch which defines __GNU_LIBRARY__ inside getopt.h
so that the correct getopt() is selected, and inside getopt.c
so that stdlib.h and unistd.h get included.

Signed-off-by: Til Kaiser <mail@tk154.de>