inotify-tools: fix link error on x86
Previous commit removed unnecessary linking with libstdc++
but introduced another error on x86 platforms:

  undefined reference to `__stack_chk_fail_local'

Fix it by explicitly linking libssp_nonshared.a

Signed-off-by: krant <aleksey.vasilenko@gmail.com>