treewide: wheel names are in lowercase (PEP 625)
Since setuptools 69.3.0, it supports PEP625,
based on this, package name and as well,
the wheel should used lowercase instead of uppercase
and also dots (.) should use underscore (_)

More details can be found here:
https://discuss.python.org/t/amending-pep-427-and-pep-625-on-package-normalization-rules/17226

Fixes:
```
Successfully built flask-2.0.2-py3-none-any.whl
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.11/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.11/site-packages/installer/__main__.py", line 86, in _main
    with WheelFile.open(args.wheel) as source:
  File "/builder/shared-workdir/build/sdk/staging_dir/target-aarch64_cortex-a53_musl/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.11/site-packages/installer/sources.py", line 162, in open
    with zipfile.ZipFile(path) as f:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/builder/shared-workdir/build/sdk/staging_dir/target-aarch64_cortex-a53_musl/usr/lib/python3.11/zipfile.py", line 1311, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/builder/shared-workdir/build/sdk/build_dir/target-aarch64_cortex-a53_musl/pypi/Flask-2.0.2//openwrt-build/Flask-2.0.2-*.whl'
```

Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>