dansguardian: Fix build error due to missing cstdlib include
Fixes the following build errors:

mipsel-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I..
-D__CONFFILE='"/etc/dansguardian/dansguardian.conf"'
-D__LOGLOCATION='"/var/log/dansguardian/"' -D__PIDDIR='"/var/run"'
-D__PROXYUSER='"root"' -D__PROXYGROUP='"root"'
-D__CONFDIR='"/etc/dansguardian"'
-I/local/users/fainelli/openwrt/trunk/staging_dir/target-mipsel-linux-gnu_glibc/usr/include
-I/local/users/fainelli/openwrt/trunk/staging_dir/target-mipsel-linux-gnu_glibc/include
-I/opt/toolchains/stbgcc-4.8-1.5/usr/include
-I/opt/toolchains/stbgcc-4.8-1.5/include    -Os -pipe -mno-branch-likely
-mips32r2 -mtune=24kc -fno-caller-saves -mips16 -minterlink-mips16
-fno-rtti  -MT dansguardian-OptionContainer.o -MD -MP -MF
.deps/dansguardian-OptionContainer.Tpo -c -o
dansguardian-OptionContainer.o `test -f 'OptionContainer.cpp' || echo
'./'`OptionContainer.cpp
OptionContainer.cpp: In member function 'void
OptionContainer::loadRooms()':
OptionContainer.cpp:796:9: error: 'exit' was not declared in this scope
   exit(1);
         ^
OptionContainer.cpp:824:10: error: 'exit' was not declared in this scope
    exit(1);
          ^
make[5]: *** [dansguardian-OptionContainer.o] Error 1

Signed-off-by: Florian Fainelli <f.fainelli@gmail.com>