libutp: deactivate -Werror
With fortify sources libutp fails to compile because the fortify sources
for musl use the GNU extension include_next. Do not fail when the
compiler issues a warning.

Fixes the following compile error:
```
In file included from libutp-2023.02.14~c95738b1/utp_utils.cpp:23:
/include/fortify/stdlib.h:22:2: error: #include_next is a GCC extension [-Werror]
   22 | #include_next <stdlib.h>
      |  ^~~~~~~~~~~~
```

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>