perl: switch to 5.30.0
The current version of perl 5.28.1 cannot be compiled on macOS 11,
because hints/darwin.sh checks only for version 10.*, and fails on 11.*
The check is fixed in 302-macos_11_support.patch, but only allows building
of perl using a single worker due to some sort of a race condition.
If multiple workers are used, the build fails with missing Errno.pm.
The race condition is corrected in perl 5.30.0 up to 5.32.0.
This patch switches to 5.30.0 to overcome the race condition,
and modifies darwin.sh to add support for building on macOS 11.
Unfortunately this is not a complete patch, beucase at the current
state, the build still fails:

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: input file: /Volumes/test/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/ipkg-install/usr/bin/perl5.30.0 is not a Mach-O file
Cannot update /Volumes/test/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/ipkg-install/usr/bin/perl5.30.0 dependency paths
make[3]: *** [makefile:445: install-all] Error 1
make[3]: Leaving directory '/Volumes/test/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0'
make[2]: *** [Makefile:152: /Volumes/test/openwrt/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/.built] Error 2

Another symptom is that with
5.30.0 build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/perl/perl-5.30.0/ipkg-install/usr/bin
contains only perl5.30.0, while with the original 5.28.1 it contains many executables.

More research is needed to find the cause of this error. Perhaps
the rest of the perl components also need to be updated. This commit
should only be used as a starting point for moving towards perl 5.30.0
or preferably the latest 5.32.0, and should not be accepted before the
above issues are resolved.

Signed-off-by: Georgi Valkov <gvalkov@abv.bg>