hamlib: link with libusb-compat instead of libusb-1.0
This hamlib package use usb.h and should link with libusb-compat,
link with libusb-1.0 makes a lot of missing symbols

  CCLD     rigctl
../src/.libs/libhamlib.so: undefined reference to `usb_find_devices'
../src/.libs/libhamlib.so: undefined reference to `usb_find_busses'
../src/.libs/libhamlib.so: undefined reference to `usb_control_msg'
../src/.libs/libhamlib.so: undefined reference to `usb_claim_interface'
../src/.libs/libhamlib.so: undefined reference to `usb_init'
../src/.libs/libhamlib.so: undefined reference to `usb_interrupt_write'
../src/.libs/libhamlib.so: undefined reference to `usb_get_driver_np'
../src/.libs/libhamlib.so: undefined reference to `usb_get_busses'
../src/.libs/libhamlib.so: undefined reference to `usb_open'
../src/.libs/libhamlib.so: undefined reference to `usb_release_interface'
../src/.libs/libhamlib.so: undefined reference to `usb_close'
../src/.libs/libhamlib.so: undefined reference to `usb_strerror'
../src/.libs/libhamlib.so: undefined reference to `usb_device'
../src/.libs/libhamlib.so: undefined reference to `usb_detach_kernel_driver_np'
../src/.libs/libhamlib.so: undefined reference to `usb_bulk_write'
../src/.libs/libhamlib.so: undefined reference to `usb_interrupt_read'
collect2: error: ld returned 1 exit status

Signed-off-by: Guo Li <uxgood.org@gmail.com>