luasql: fix compile with mariadb-10.2.x
This is in anticipation of the mariadb upgrade to 10.2.x. luasql compile
fails:

In file included from src/ls_mysql.c:21:0:
src/ls_mysql.c: In function 'luaopen_luasql_mysql':
src/ls_mysql.c:605:25: error: expected ')' before 'MYSQL_SERVER_VERSION'
     lua_pushliteral (L, MYSQL_SERVER_VERSION);
                         ^
src/ls_mysql.c:605:5: error: too few arguments to function 'lua_pushlstring'
     lua_pushliteral (L, MYSQL_SERVER_VERSION);
     ^
/home/equeiroz/src/openwrt-asus/staging_dir/target-mipsel_74kc_musl/usr/include/lua.h:175:16: note: declared here
 LUA_API void  (lua_pushlstring) (lua_State *L, const char *s, size_t l);
                ^~~~~~~~~~~~~~~

To fix this cherry-pick upstream commit
6df3f672313f8dbca219199c8ec8d20c0247347f.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>