lcd4linux: fix build error for custom build
This change fixes the following build error:
hecking that generated files are newer than configure... done
configure: error: conditional "ANSICXX" was never defined.
Usually this means the macro was only invoked conditionally.
make[2]: *** [Makefile:300:
/home/feckert/openwrt/build_dir/target-x86_64_musl/lcd4linux-custom/lcd4linux-2019-07-19-0b83bb3a/.configured_a17fb5ef857664f03cd0ce37cc5ea591]
Error 1
make[2]: Leaving directory
'/home/feckert/feeds/packages/utils/lcd4linux'
time: package/feeds/packages/lcd4linux/custom/compile#15.43#0.79#16.92
	ERROR: package/feeds/packages/lcd4linux failed to build (build
variant: custom).
make[1]: *** [package/Makefile:120:
package/feeds/packages/lcd4linux/compile] Error 1
make[1]: Leaving directory
'/home/feckert/openwrt'
make: ***
[/home/feckert/openwrt/include/toplevel.mk:231:
package/feeds/packages/lcd4linux/compile] Error 2

Signed-off-by: Florian Eckert <fe@dev.tdt.de>
Suggested-by: Oskari Rauta <oskari.rauta@gmail.com>
(cherry picked from commit 917ea9d214fe4a6ef8e000c50761ac6d302f8162)