luasec: use gcc to link instead of ld
Linking with ld is not portable and was causing problems for some
targets, e.g. i386_pentium4:
i486-openwrt-linux-musl-ld: x509.o: in function `push_asn1_objname':
x509.c:(.text+0x61): undefined reference to `__stack_chk_fail_local'
...

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>