opencv: fix musl compatibility
 - Turn off precompiled header support since it leads to following
   linking failure:

    .../staging_dir/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.10/mips-openwrt-linux-musl/lib/crt1.o: In function `__start':
    (.text+0xc): undefined reference to `main'
    collect2: error: ld returned 1 exit status

 - Replace `sys/sysctl.h` includes with `linux/sysctl.h` ones as the musl libc
   does not provide this nonstandard header. This has also been fixed upstream
   in the OpenCV 3.x releases

Signed-off-by: Jo-Philipp Wich <jow@openwrt.org>