libftdi1: disable building documentation
This fixes the following build failure:

[ 66%] Generating ../doc/xml/ftdi_8c.xml
warning: Tag 'PERL_PATH' at line 2083 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'MSCGEN_PATH' at line 2105 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
[ 72%] Generating ftdi1_doc.i
Traceback (most recent call last):
  File "/home/stijn/Development/LEDE/source/build_dir/target-x86_64_musl/libftdi1-1.4/python/doxy2swig.py", line 457, in <module>
    main()
  File "/home/stijn/Development/LEDE/source/build_dir/target-x86_64_musl/libftdi1-1.4/python/doxy2swig.py", line 453, in main
    convert(args[0], args[1], not options.func_def, options.quiet)
  File "/home/stijn/Development/LEDE/source/build_dir/target-x86_64_musl/libftdi1-1.4/python/doxy2swig.py", line 430, in convert
    p = Doxy2SWIG(input, include_function_definition, quiet)
  File "/home/stijn/Development/LEDE/source/build_dir/target-x86_64_musl/libftdi1-1.4/python/doxy2swig.py", line 72, in __init__
    f = my_open_read(src)
  File "/home/stijn/Development/LEDE/source/build_dir/target-x86_64_musl/libftdi1-1.4/python/doxy2swig.py", line 44, in my_open_read
    return open(source)
FileNotFoundError: [Errno 2] No such file or directory: '/home/stijn/Development/LEDE/source/build_dir/target-x86_64_musl/libftdi1-1.4/doc/xml/ftdi_8c.xml'

Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>
Acked-by: Rosen Penev <rosenp@gmail.com>
(cherry picked from commit c13184366330a72ffd909b605e5a3fb874f23077)