libtheora: use CONFIGURE_ARGS, fix build on armeb
Use CONFIGURE_ARGS instead of defining a custom Build/Configure target.
Set --disable-asm on armeb to fix build error:
  CC       apiwrapper.lo
In file included from state.h:56,
                 from apiwrapper.h:24,
                 from apiwrapper.c:21:
arm/armint.h:24:5: error: #error "Big-endian configurations are not supported by the ARM asm. " "Reconfigure with --disable-asm or undefine OC_ARM_ASM."
   24 | #   error "Big-endian configurations are not supported by the ARM asm. " \
      |     ^~~~~

Signed-off-by: Daniel Golle <daniel@makrotopia.org>