grilo-plugins: adjust CONFIGURE_ARGS
Removed unused flags, and added --enable-compile-warnings=minimum to
avoid a build failure with fortify-headers:
In file included from [staging_dir/target]/usr/include/libxml2/libxml/tree.h:15:0,
                 from [staging_dir/target]/usr/include/libxml2/libxml/parser.h:16,
                 from grl-jamendo.c:32:
[staging_dir/toolchain]/include/fortify/stdio.h: In function 'snprintf':
[staging_dir/toolchain]/include/fortify/stdio.h:99:2: error: format not
a string literal, argument types not checked [-Werror=format-nonliteral]
  return __orig_snprintf(__s, __n, __f, __builtin_va_arg_pack());
  ^~~~~~

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>