micropython: fix stackctrl compilation for GCC 13
On host PC using GCC 13, stackctrl.c fails to compile
with the following error:

../py/stackctrl.c: In function 'mp_stack_ctrl_init':
../py/stackctrl.c:32:32: error: storing the address of
   local variable 'stack_dummy'
   in 'mp_state_ctx.thread.stack_top' [-Werror=dangling-pointer=]
   32 |     MP_STATE_THREAD(stack_top) = (char *)&stack_dummy;
../py/stackctrl.c:31:18: note: 'stack_dummy' declared here
   31 |     volatile int stack_dummy;
      |                  ^~~~~~~~~~~
In file included from ../py/runtime.h:29,
                 from ../py/stackctrl.c:27:
../py/mpstate.h:296:23: note: 'mp_state_ctx' declared here
  296 | extern mp_state_ctx_t mp_state_ctx;
      |                       ^~~~~~~~~~~~
cc1: all warnings being treated as errors

Fixed accordingly by ignoring -dangling-pointer warning
inside mp_stack_ctrl_init function.

Signed-off-by: Jean-Paul Etienne <fractalclone@gmail.com>
(cherry picked from commit 4c1b74ede3a1d8c5b8b1594a01a2048325ee6c23)