snapcast: fix PulseAudio
While testing my integration of Snapcast, I didn't test with CONFIG_ALL*
and CONFIG_BUILDBOT flags, but the buildbots did and failed with a lot
of undefined reference to PulseAudio.

Fix it with preventing PulseAudio detection.
While at it, prevent Avahi detection too to save more flash space.

These features will be available later, through flavours.

Fixes: https://github.com/openwrt/packages/pull/23956
Fixes: eeb8d131fc93 ("snapcast: add package snapserver and snapclient")

Signed-off-by: Szabolcs Hubai <szab.hu@gmail.com>