vim/host: fix build failures
Indeterminably vim/host fails on the build bots:

objects/fileio.o: In function `readfile':
fileio.c:(.text+0x5b3f): undefined reference to `libiconv_close'
fileio.c:(.text+0x61ad): undefined reference to `libiconv_close'
fileio.c:(.text+0x62f6): undefined reference to `libiconv'
fileio.c:(.text+0x6794): undefined reference to `libiconv_close'
objects/fileio.o: In function `buf_write_bytes':
fileio.c:(.text+0xa1fe): undefined reference to `libiconv'
fileio.c:(.text+0xa54a): undefined reference to `libiconv'
objects/fileio.o: In function `buf_write':
fileio.c:(.text+0xaf48): undefined reference to `libiconv_close'
objects/mbyte.o: In function `my_iconv_open.part.18':
mbyte.c:(.text+0x2ced): undefined reference to `libiconv_open'
mbyte.c:(.text+0x2d3a): undefined reference to `libiconv'
mbyte.c:(.text+0x2d5f): undefined reference to `libiconv_close'
objects/mbyte.o: In function `convert_setup_ext':
mbyte.c:(.text+0x33bf): undefined reference to `libiconv_close'
objects/mbyte.o: In function `string_convert_ext':
mbyte.c:(.text+0x363c): undefined reference to `libiconv'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
Makefile:1949: recipe for target 'vim' failed

This is addressed by pulling in libiconv/host. Also configure switches
are added that keep external dependencies to a minimum, for instance
avoiding to link to X11 or gettext.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>
(cherry-picked from dc727a2430e99b928dec9100135fc215a78138fd)