netatop: fix compilation warning for kernel module
Fix compilation warning for missing fallthrough.
Fix compilation warning:
/builder/shared-workdir/build/build_dir/target-mipsel_24kc_musl/netatop-3.1/module/netatop.c: In function 'getsockopt':
/builder/shared-workdir/build/build_dir/target-mipsel_24kc_musl/netatop-3.1/module/netatop.c:1619:26: error: this statement may fall through [-Werror=implicit-fallthrough=]
 1619 |                 tasktype = 'g';
      |                 ~~~~~~~~~^~~~~
/builder/shared-workdir/build/build_dir/target-mipsel_24kc_musl/netatop-3.1/module/netatop.c:1621:12: note: here
 1621 |            case NETATOP_GETCNT_PID:
      |            ^~~~
cc1: all warnings being treated as errors

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>