privoxy: bump to version 4.0.0
Bump privoxy to version 4.0.0. Every PCRE2 patch got merged and this
also fix compilation error currently present with the package.

filters.c: In function 'get_filter_function':
filters.c:2104:23: error: assignment to 'filter_function_ptr' {aka 'char * (*)(void)'} from incompatible pointer type 'char * (*)(struct client_state *)' [-Wincompatible-pointer-types]
 2104 |       filter_function = pcrs_filter_response_body;
      |                       ^
filters.c:2109:23: error: assignment to 'filter_function_ptr' {aka 'char * (*)(void)'} from incompatible pointer type 'char * (*)(struct client_state *)' [-Wincompatible-pointer-types]
 2109 |       filter_function = gif_deanimate_response;
      |                       ^
filters.c: In function 'execute_content_filters':
filters.c:2547:42: error: too many arguments to function 'content_filter'
 2547 |    content = (content_filter != NULL) ? (*content_filter)(csp) : NULL;
      |                                         ~^~~~~~~~~~~~~~~~

Reading the Changelog, no regression should arise from the package bump.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>