mdnsresponder: (fix build) use TARGET_CC as LD
Probably related to -fstack-protector being used.
Got the idea from:
  http://ubuntuforums.org/showthread.php?t=352642&p=10100263#post10100263
  Regarding the missing __stack_check_fail_local, using gcc as the linker instead of ld fixes the issue without disabling stack protection as with -fno-stack-protector.

Fixes linker errs on some targets:
  objects/prod/dnssd_clientstub.c.so.o: In function `handle_resolve_response':
  dnssd_clientstub.c:(.text+0x395): undefined reference to `__stack_chk_fail_local'
  objects/prod/dnssd_clientstub.c.so.o: In function `handle_query_response':
  dnssd_clientstub.c:(.text+0x4bd): undefined reference to `__stack_chk_fail_local'

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>