gzip: update to version 1.14
Add TARGET_CFLAGS += -std=gnu17
to fix following error discovered by CI/CD:
2025-09-30T23:53:47.3168066Z In file included from gzip.c:66:
2025-09-30T23:53:47.3189341Z gzip.c:131:34: error: expected declaration specifiers or '...' before numeric constant
2025-09-30T23:53:47.3190258Z   131 | # define BUFFER_ALIGNED alignas (4096)
2025-09-30T23:53:47.3190760Z       |                                  ^~~~
2025-09-30T23:53:47.3191259Z gzip.h:108:39: note: in definition of macro 'DECLARE'
2025-09-30T23:53:47.3191864Z   108 | #  define DECLARE(type, array, size)  type array[size]
2025-09-30T23:53:47.3192411Z       |                                       ^~~~
2025-09-30T23:53:47.3192942Z gzip.c:135:13: note: in expansion of macro 'BUFFER_ALIGNED'
2025-09-30T23:53:47.3193587Z   135 | DECLARE(uch BUFFER_ALIGNED, inbuf,  INBUFSIZ +INBUF_EXTRA);
2025-09-30T23:53:47.3194137Z       |             ^~~~~~~~~~~~~~
2025-09-30T23:53:47.3194752Z gzip.c:131:34: error: expected declaration specifiers or '...' before numeric constant
2025-09-30T23:53:47.3195442Z   131 | # define BUFFER_ALIGNED alignas (4096)
2025-09-30T23:53:47.3195880Z       |                                  ^~~~
2025-09-30T23:53:47.3196330Z gzip.h:108:39: note: in definition of macro 'DECLARE'
2025-09-30T23:53:47.3197297Z   108 | #  define DECLARE(type, array, size)  type array[size]
2025-09-30T23:53:47.3197829Z       |                                       ^~~~
2025-09-30T23:53:47.3198342Z gzip.c:136:13: note: in expansion of macro 'BUFFER_ALIGNED'
2025-09-30T23:53:47.3199113Z   136 | DECLARE(uch BUFFER_ALIGNED, outbuf, OUTBUFSIZ+OUTBUF_EXTRA);
2025-09-30T23:53:47.3199957Z       |             ^~~~~~~~~~~~~~
2025-09-30T23:53:47.3200589Z gzip.c:131:34: error: expected declaration specifiers or '...' before numeric constant
2025-09-30T23:53:47.3201250Z   131 | # define BUFFER_ALIGNED alignas (4096)
2025-09-30T23:53:47.3201688Z       |                                  ^~~~
2025-09-30T23:53:47.3202128Z gzip.h:108:39: note: in definition of macro 'DECLARE'
2025-09-30T23:53:47.3202665Z   108 | #  define DECLARE(type, array, size)  type array[size]
2025-09-30T23:53:47.3203150Z       |                                       ^~~~
2025-09-30T23:53:47.3203642Z gzip.c:138:13: note: in expansion of macro 'BUFFER_ALIGNED'
2025-09-30T23:53:47.3204203Z   138 | DECLARE(uch BUFFER_ALIGNED, window, 2L*WSIZE);
2025-09-30T23:53:47.3204684Z       |             ^~~~~~~~~~~~~~

- Release announcement:
https://lists.gnu.org/archive/html/info-gnu/2025-04/msg00007.html

Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>
(cherry picked from commit 3bf64e39b281b9736fbbd6acf52c18e6d595f50c)