docker-compose: [WIP] Update to version 5.0.0
 - Build fails with:

Finding targets
no required module provides package github.com/docker/compose/v2/cmd; to add it:
	go get github.com/docker/compose/v2/cmd

Building targets
no Go files in ./build_dir/target-x86_64_musl/compose-5.0.0/.go_work/build

make[2]: *** [Makefile:50: ./build_dir/target-x86_64_musl/compose-5.0.0/.built] Error 1
make[2]: Leaving directory './feeds/packages/utils/docker-compose'
time: package/feeds/packages/docker-compose/compile#0.52#0.55#2.28
    ERROR: package/feeds/packages/docker-compose failed to build.
make[1]: *** [package/Makefile:187: package/feeds/packages/docker-compose/compile] Error 1
make: *** [./include/toplevel.mk:233: package/feeds/packages/docker-compose/compile] Error 2

Signed-off-by: Javier Marcet <javier@marcet.info>