open-plc-utils: upgrade to latest git revision and fix compilation
Buildbots are reporting the following error:
../mme/ARPCPrint.c: In function 'ARPCPrint':
../mme/ARPCPrint.c:123:2: error: incompatible type for argument 3 of 'vfprintf'
  vfprintf (fp, (char *)(&data->LIST [LE16TOH (data->STROFFSET)]), (void *)(&data->LIST [LE16TOH (data->ARGOFFSET)]));
  ^
In file included from /store/buildbot/slave/mxs/build/staging_dir/toolchain-arm_arm926ej-s_gcc-4.8-linaro_musl-1.1.11_eabi/include/fortify/stdio.h:20:0,
                 from ../mme/ARPCPrint.c:68:
/store/buildbot/slave/mxs/build/staging_dir/toolchain-arm_arm926ej-s_gcc-4.8-linaro_musl-1.1.11_eabi/include/stdio.h:108:5: note: expected '__isoc_va_list' but argument is of type 'void *'

Fix this by definition __UCLIBC__ to enable a workaround for this
issue.

While at, switch to HTTPS URL for cloning the git repo.

Signed-off-by: Michael Heimpold <mhei@heimpold.de>