libcanfestival: skip building examples
At the moment, LEDE buildbots are complaining with:

-snip-
...
libcanfestival/examples/TestMasterSlave/TestMasterSlave.c:50: undefined reference to `MasterMap1'
TestMasterSlave.o: In function `InitNodes':
...
-snap-

Since we are only interessted in the library itself, skip compilation
of the example code. This should both fix the build and speedup it
a little bit.

Signed-off-by: Michael Heimpold <mhei@heimpold.de>