xr_usb_serial_common: fix compilation warning
Add patch fixing compilation warning due to unused function.
Fix compilation warning:
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/usb-serial-xr_usb_serial_common-2022-03-30-ecc6ebe0/xr_usb_serial_common-1a/xr_usb_serial_common.c: In function 'xr_usb_serial_ctrl_irq':
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/usb-serial-xr_usb_serial_common-2022-03-30-ecc6ebe0/xr_usb_serial_common-1a/xr_usb_serial_common.c:261:28: error: unused variable 'tty' [-Werror=unused-variable]
  261 |         struct tty_struct *tty;
      |                            ^~~
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/usb-serial-xr_usb_serial_common-2022-03-30-ecc6ebe0/xr_usb_serial_common-1a/xr_usb_serial_common.c: In function 'xr_usb_serial_process_read_urb':
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/usb-serial-xr_usb_serial_common-2022-03-30-ecc6ebe0/xr_usb_serial_common-1a/xr_usb_serial_common.c:393:28: error: unused variable 'tty' [-Werror=unused-variable]
  393 |         struct tty_struct *tty;
      |                            ^~~
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/usb-serial-xr_usb_serial_common-2022-03-30-ecc6ebe0/xr_usb_serial_common-1a/xr_usb_serial_common.c: In function 'xr_usb_serial_softint':
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/usb-serial-xr_usb_serial_common-2022-03-30-ecc6ebe0/xr_usb_serial_common-1a/xr_usb_serial_common.c:468:28: error: unused variable 'tty' [-Werror=unused-variable]
  468 |         struct tty_struct *tty;
      |                            ^~~
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/usb-serial-xr_usb_serial_common-2022-03-30-ecc6ebe0/xr_usb_serial_common-1a/xr_usb_serial_common.c: In function 'xr_usb_serial_reset_resume':
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/usb-serial-xr_usb_serial_common-2022-03-30-ecc6ebe0/xr_usb_serial_common-1a/xr_usb_serial_common.c:1634:28: error: unused variable 'tty' [-Werror=unused-variable]
 1634 |         struct tty_struct *tty;
      |                            ^~~
cc1: all warnings being treated as errors

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>