nvme-cli: update to 2.11
Bump to latest upstream release.

Removed upstreamed: 020-replace_uint16_t
Manually rebased: 010-gcc14.patch

To fix the following build error, added two commits from upstream:
020-nvme-print-add-fallback-for-.patch
021-pligins-netapp-add-include-of-libgen.h-for-basename.patch

Tested the resulting binary and it seems fine:
% nvme smart-log /dev/nvme0 | grep "temperature"
temperature				: 42 °C (315 K)

Link to upstream issue: https://github.com/linux-nvme/nvme-cli/issues/2743

Build error:
../nvme-print.c: In function 'is_temperature_fahrenheit':
../nvme-print.c:805:19: error: 'LC_MEASUREMENT' undeclared (first use in this function)
  805 |         setlocale(LC_MEASUREMENT, "");
      |                   ^~~~~~~~~~~~~~
../nvme-print.c:805:19: note: each undeclared identifier is reported only once for each function it appears in

Build system: x86/64
Build-tested: x86/64
Run-tested: x86/64

Signed-off-by: John Audia <therealgraysky@proton.me>