adguardhome: update quic-go to v0.37.6
* quic-go v0.36.x cannot be compiled with Go 1.21. Update that
  AdGuardHome dependency to latest one from v0.37 series.
* It fixes following compilation error:
  go-mod-cache/github.com/quic-go/quic-go@v0.36.2/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.
  com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet.

Signed-off-by: Dobroslaw Kijowski <dobo90@gmail.com>
(cherry picked from commit 11230bb580443efd14a3c3bb4aa193c0476e4a7d)