rsync: fix compilation for undefined reference ot makedev
This change fixes the following compilation error for rsync

generator.c:(.text+0x4872): undefined reference to `makedev'

Glibc removes sys/sysmacros.h which defines makedev from sys/types.h
since v2.28.

Signed-off-by: Florian Eckert <fe@dev.tdt.de>