xtables-addons: fix build for kernel 6.12
    missing prototypes for three functions generated build errors.
	error: no previous prototype for 'foo' [-Werror=missing-prototypes]

	extensions/LUA/prot_buf_helpers.c: get_header_size
	extensions/LUA/prot_buf_tftp.c: tftp_get_field_changes
	extensions/LUA/prot_buf_dynamic.c: free_dynamic_prot_buf

Signed-off-by: Russell Senior <russell@personaltelco.net>