python-cython: update to version 3.1.5
Fixes:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/turris/build/staging_dir/hostpkg/lib/python3.11/site-packages/installer/__main__.py", line 98, in <module>
_main(sys.argv[1:], "python -m installer")
  File "/turris/build/staging_dir/hostpkg/lib/python3.11/site-packages/installer/__main__.py", line 86, in _main
with WheelFile.open(args.wheel) as source:
  File "/turris/build/staging_dir/hostpkg/lib/python3.11/contextlib.py", line 137, in __enter__
return next(self.gen)
   ^^^^^^^^^^^^^^
  File "/turris/build/staging_dir/hostpkg/lib/python3.11/site-packages/installer/sources.py", line 162, in open
with zipfile.ZipFile(path) as f:
 ^^^^^^^^^^^^^^^^^^^^^
  File "/turris/build/staging_dir/hostpkg/lib/python3.11/zipfile.py", line 1311, in __init__
self.fp = io.open(file, filemode)
  ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/turris/build/build_dir/hostpkg/pypi/Cython-3.0.10//openwrt-build/Cython-3.0.10-*.whl'

Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>