jool: fix compilation warning
Add patch fixing compilation warning due to wrong cast.
Fix compilation warning:
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/xlator.c: In function 'offset_equals':
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/xlator.c:878:32: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  878 |         return (offset->ns == ((__u64)instance->jool.ns & 0xFFFFFFFF))
      |                                ^
cc1: all warnings being treated as errors

In file included from ./include/linux/kernel.h:19,
                 from ./include/linux/skbuff.h:13,
                 from /home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/../../mod/common/skbuff.h:4,
                 from /home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/skbuff.c:1:
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/skbuff.c: In function 'print_skb_fields':
./include/linux/kern_levels.h:5:25: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'int' [-Werror=format=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
./include/linux/printk.h:422:25: note: in definition of macro 'printk_index_wrap'
  422 |                 _p_func(_fmt, ##__VA_ARGS__);                           \
      |                         ^~~~
./include/linux/printk.h:535:9: note: in expansion of macro 'printk'
  535 |         printk(KERN_CONT fmt, ##__VA_ARGS__)
      |         ^~~~~~
./include/linux/kern_levels.h:24:25: note: in expansion of macro 'KERN_SOH'
   24 | #define KERN_CONT       KERN_SOH "c"
      |                         ^~~~~~~~
./include/linux/printk.h:535:16: note: in expansion of macro 'KERN_CONT'
  535 |         printk(KERN_CONT fmt, ##__VA_ARGS__)
      |                ^~~~~~~~~
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/skbuff.c:38:17: note: in expansion of macro 'pr_cont'
   38 |                 pr_cont(text "\n", ##__VA_ARGS__); \
      |                 ^~~~~~~
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/skbuff.c:112:9: note: in expansion of macro 'print'
  112 |         print(tabs, "data:%ld", skb->data - skb->head);
      |         ^~~~~
./include/linux/kern_levels.h:5:25: error: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'sk_buff_data_t' {aka 'unsigned char *'} [-Werror=format=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
./include/linux/printk.h:422:25: note: in definition of macro 'printk_index_wrap'
  422 |                 _p_func(_fmt, ##__VA_ARGS__);                           \
      |                         ^~~~
./include/linux/printk.h:535:9: note: in expansion of macro 'printk'
  535 |         printk(KERN_CONT fmt, ##__VA_ARGS__)
      |         ^~~~~~
./include/linux/kern_levels.h:24:25: note: in expansion of macro 'KERN_SOH'
   24 | #define KERN_CONT       KERN_SOH "c"
      |                         ^~~~~~~~
./include/linux/printk.h:535:16: note: in expansion of macro 'KERN_CONT'
  535 |         printk(KERN_CONT fmt, ##__VA_ARGS__)
      |                ^~~~~~~~~
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/skbuff.c:38:17: note: in expansion of macro 'pr_cont'
   38 |                 pr_cont(text "\n", ##__VA_ARGS__); \
      |                 ^~~~~~~
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/skbuff.c:113:9: note: in expansion of macro 'print'
  113 |         print(tabs, "tail:%u", skb->tail);
      |         ^~~~~
./include/linux/kern_levels.h:5:25: error: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'sk_buff_data_t' {aka 'unsigned char *'} [-Werror=format=]
    5 | #define KERN_SOH        "\001"          /* ASCII Start Of Header */
      |                         ^~~~~~
./include/linux/printk.h:422:25: note: in definition of macro 'printk_index_wrap'
  422 |                 _p_func(_fmt, ##__VA_ARGS__);                           \
      |                         ^~~~
./include/linux/printk.h:535:9: note: in expansion of macro 'printk'
  535 |         printk(KERN_CONT fmt, ##__VA_ARGS__)
      |         ^~~~~~
./include/linux/kern_levels.h:24:25: note: in expansion of macro 'KERN_SOH'
   24 | #define KERN_CONT       KERN_SOH "c"
      |                         ^~~~~~~~
./include/linux/printk.h:535:16: note: in expansion of macro 'KERN_CONT'
  535 |         printk(KERN_CONT fmt, ##__VA_ARGS__)
      |                ^~~~~~~~~
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/skbuff.c:38:17: note: in expansion of macro 'pr_cont'
   38 |                 pr_cont(text "\n", ##__VA_ARGS__); \
      |                 ^~~~~~~
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/skbuff.c:114:9: note: in expansion of macro 'print'
  114 |         print(tabs, "end:%u", skb->end);
      |         ^~~~~
cc1: all warnings being treated as errors

/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/nl/instance.c: In function 'serialize_instance':
/home/ansuel/openwrt-ansuel/openwrt/build_dir/target-mips-openwrt-linux-musl_musl/linux-lantiq_xrx200/jool-4.1.8/src/mod/common/nl/instance.c:40:46: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
   40 |         error = nla_put_u32(skb, JNLAIE_NS, ((__u64)entry->ns) & 0xFFFFFFFF);
      |                                              ^
cc1: all warnings being treated as errors

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>