dnsdist: disable XSK to fix the build
XSK support is set to auto by default and on some hosts it is detected as
on and leads to:

```
In file included from dnsdist-backend.cc:32:
xsk.hh:28:10: fatal error: bits/types/struct_timespec.h: No such file or
directory
   28 | #include <bits/types/struct_timespec.h>
```

Here we disable XSK so configure will behave more deterministically and
hopefully fix the builders.

Signed-off-by: krant <aleksey.vasilenko@gmail.com>