iotivity: add patch for g++-7.10 compatibily
This applies upstream commit 26c2798 that adds the funcional header,
avoiding errors with 'std' namespace functions, like:
resource/include/OCUtilities.h:85:21: error: 'bind' is not a member of
'std'

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>