btrfs-progs: fix linking to libattr
I got the following error:
mkfs.o: In function `add_xattr_item':
mkfs.c:(.text+0x5dc): undefined reference to `llistxattr'
mkfs.c:(.text+0x748): undefined reference to `getxattr'
props.o: In function `prop_compression':
props.c:(.text+0x154): undefined reference to `fsetxattr'
props.c:(.text+0x198): undefined reference to `fgetxattr'
props.c:(.text+0x240): undefined reference to `fgetxattr'
collect2: error: ld returned 1 exit status

Fix it, by forcing btrfs-progs to link to libattr. While at it,
correct the dependency to libattr (instead of the tool attr).

Signed-off-by: Stefan Hellermann <stefan@the2masters.de>