xinetd: fix musl compatibility
Pass HAVE_RLIM_T via TARGET_CPPFLAGS since configure uses that define
but never actually declares it.

Without doing that, `config.h` tries to declare `rlim_t` itself which
leads to `config.h:126:16: error: 'long long long' is too long for GCC`
with musl on at least x86_64.

Also refresh patches while we're at it.

Signed-off-by: Jo-Philipp Wich <jow@openwrt.org>