fping: Set -std=gnu99 to fix build errors due to C99 constructs
Fixes build errors such as:

mipsel-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I..
-I/home/florian/dev/openwrt/trunk/staging_dir/target-mipsel-unknown-linux-gnu_glibc/usr/include
-I/home/florian/dev/openwrt/trunk/staging_dir/target-mipsel-unknown-linux-gnu_glibc/include
-I/home/florian/dev/toolchains/stbgcc-4.8-1.5/usr/include
-I/home/florian/dev/toolchains/stbgcc-4.8-1.5/include  -Wall -Wextra
-Wno-sign-compare -DIPV6 -Os -pipe -mno-branch-likely -mips32r2
-mtune=24kc -fno-caller-saves -Wno-unused-result  -D_FORTIFY_SOURCE=1
-Wl,-z,now -Wl,-z,relro  -MT fping-optparse.o -MD -MP -MF
.deps/fping-optparse.Tpo -c -o fping-optparse.o `test -f 'optparse.c' ||
echo './'`optparse.c
optparse.c: In function 'permute':
optparse.c:55:5: error: 'for' loop initial declarations are only allowed
in C99 mode
     for (int i = index; i < options->optind - 1; i++)
     ^
optparse.c:55:5: note: use option -std=c99 or -std=gnu99 to compile your
code
optparse.c: In function 'optstring_from_long':
optparse.c:160:5: error: 'for' loop initial declarations are only
allowed in C99 mode
     for (int i = 0; !longopts_end(longopts, i); i++) {

Signed-off-by: Florian Fainelli <f.fainelli@gmail.com>