dnsdist: update to 2.0.6
Bump from 2.0.1 to the latest 2.0 LTS release. This pulls in
upstream commit 53cb738795 ("dnsdist: make code boost-1.91
compatible", Otto Moerbeek, 2026-04-29), which fixes the build
break against Boost 1.91 currently shipped by OpenWrt:

  dnsdist-lua.cc:3086:101: error: converting to
    'boost::optional<unordered_map<...>>' from initializer list
    would use explicit constructor 'constexpr boost::optional<T>::
    optional(U&&) [...]'

Signed-off-by: Alexandru Ardelean <alex@shruggie.ro>