remove unnecessary libiconv dependencies
The compiled libaprutil library contains references to libiconv,
libiconv_open and libiconv_close functions from the full gettext
package even when the full gettext support is disabled (i.e. the
CONFIG_BUILD_NLS configuration parameter is not set). The dependency
on these ICONV functions breaks compilation of some packages that
depend on libaprutil, such as subversion:

<targetdir>/usr/lib/libaprutil-1.so: undefined reference to `libiconv'
<targetdir>/usr/lib/libaprutil-1.so: undefined reference to `libiconv_open'
<targetdir>/usr/lib/libaprutil-1.so: undefined reference to `libiconv_close'

Signed-off-by: Don Rumata <don.rumata.vk@gmail.com>