shine: fix mips64 (octeon) build error
error reported by buildbot, replicated locally:
wave.c:(.text+0x8e4): undefined reference to `__builtin_bswap16'

It seems that gcc builtin function is not working for mips64

according to
https://gcc.gnu.org/ml/gcc-patches/2014-01/msg00551.html
bswap patterns only work in >4.8 so the compiler
check in wave.c seems inconsistent across different archs
as octeon has gcc 4.6

make it require gcc >=4.8

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>