bandwidthd: fix undefined references to inline functions
gcc-7 with -Os makes inline functions disappeard. It are caused by
the new C11 inline semantics. pass option -fgnu89-inline to gcc let
it use gnu inline semantics.
see https://wiki.debian.org/GCC7#Porting_help

bandwidthd.o: In function `RCDF_Load':
bandwidthd.c:(.text+0xb33): undefined reference to `FindIp'
bandwidthd.o: In function `PacketCallback':
bandwidthd.c:(.text+0x11d0): undefined reference to `FindIp'
bandwidthd.c:(.text+0x11e2): undefined reference to `Credit'
bandwidthd.c:(.text+0x11ea): undefined reference to `FindIp'
bandwidthd.c:(.text+0x11fc): undefined reference to `Credit'
bandwidthd.c:(.text+0x1218): undefined reference to `FindIp'
bandwidthd.c:(.text+0x122a): undefined reference to `Credit'
bandwidthd.c:(.text+0x1232): undefined reference to `FindIp'
bandwidthd.c:(.text+0x1244): undefined reference to `Credit'
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'bandwidthd' failed
make[4]: *** [bandwidthd] Error 1

Signed-off-by: Guo Li <uxgood.org@gmail.com>