Revert "scapy: fix build by including pip requirements"
1. This commit was pushed to the master branch without review,
it is causing that scapy is not compiled anymore due to
wrong hashes.

This error from the buildbots:
Collecting packaging==25.0 (from -r ./host-pip-requirements.txt (line 1))
  Using cached packaging-25.0.tar.gz (165 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    packaging==25.0 from https://files.pythonhosted.org/packages/a1/d4/1fc4078c65507b51b96ca8f8c3ba19e6a61c8253c72794544580a7b6c24d/packaging-25.0.tar.gz (from -r ./host-pip-requirements.txt (line 1)):
        Expected sha256 29572ef2b1f17581046b3a2227d5c611fb25ec70ca1ba8554b24b0e69331a484
             Got        d443872c98d677bf60f6a1f2f8c1cb748e8fe762d2bf9d3148b5599295b0fc4f

make[3]: *** [Makefile:46: /builder/shared-workdir/build/sdk/build_dir/target-arm_cortex-a9+neon_musl_eabi/pypi/scapy-2.6.1/.built] Error 1
time: package/feeds/packages/scapy/compile#1.15#0.41#1.71

2. While at it, the commit implements old solution by using host-pip-requirements
This was removed in https://github.com/openwrt/packages/pull/20657

This reverts commit ebb0ed3ba2cbcc64b20ce21010b6aad7c9abff29.

Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>