php7: fix build of php7-mod-intl
This fixes the following build error (shortened paths for readability):

-snip-
In file included from .../php-7.1.4/ext/intl/intl_convertcpp.h:26:0,
                 from .../php-7.1.4/ext/intl/intl_convertcpp.cpp:21:
.../staging_dir/target-arm_arm926ej-s_musl_eabi/usr/include/unicode/unistr.h:56:16: error: 'UChar' does not name a type
 u_strlen(const UChar *s);
                ^
.../staging_dir/target-arm_arm926ej-s_musl_eabi/usr/include/unicode/unistr.h:80:19: error: 'char16_t' has not been declared
                   char16_t *dest, int32_t destCapacity,
                   ^
.../staging_dir/target-arm_arm926ej-s_musl_eabi/usr/include/unicode/unistr.h:81:25: error: 'char16_t' does not name a type
                   const char16_t *src, int32_t srcLength,
                         ^
In file included from .../php-7.1.4/ext/intl/intl_convertcpp.h:26:0,
                 from .../php-7.1.4/ext/intl/intl_convertcpp.cpp:21:
.../staging_dir/target-arm_arm926ej-s_musl_eabi/usr/include/unicode/unistr.h:462:16: error: 'char16_t' does not name a type
          const char16_t *srcChars) const;
                ^
[...]
-snap-

This build error was introduced by update of icu to 59.1.

Signed-off-by: Michael Heimpold <mhei@heimpold.de>