libs/speexdsp: prevent NEON breakage
The speexdsp resampler received some NEON optimizations in 1.2rc2. The
configure parameter --enable-neon is misleading, because even if it's
not used NEON optimizations get applied. This leads to build failures on
some ARMs, e.g. aarch64_generic:

  CC       resample.lo
In file included from resample.c:104:0:
resample.c: In function 'resampler_basic_direct_single':
resample_neon.h:148:5: error: impossible constraint in 'asm'
     asm volatile ("  cmp %[len], #0\n"
     ^
Makefile:537: recipe for target 'resample.lo' failed

Prevent this by forcibly disabling the optimizations (--enable-neon=no).

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>