mox-pkcs11: fix broken Makefile
The mox-pkcs11 package was merged with a Makefile that fails during build,
specifically because of linking issues.

Example errors:

> mox-pkcs11.c:(.text+0x1e4): undefined reference to `find_key_by_type_and_desc'
> mox-pkcs11.c:(.text+0x109c): undefined reference to `keyctl_read'
> ERROR: package/feeds/packages/mox-pkcs11 failed to build.

The specific error is a missing '\'.

Reported-by: Robert Klink <rklink@ripe.net>
Signed-off-by: Trix Taiclet <git@trix.moe>