luasec: fix build with OPENSSL_NO_COMP
Currently luasec fails to build if OpenSSL was built without compression
support due to an undefined COMP_METHOD type:

    ssl.c: In function 'meth_compression':
    ssl.c:404:9: error: unknown type name 'COMP_METHOD'
       const COMP_METHOD *comp;
             ^
    <builtin>: recipe for target 'ssl.o' failed
    make[6]: *** [ssl.o] Error 1

Add a local patch to stub the `meth_compression()` function if there is no
compression support available in the OpenSSL library in order to allow
luasec to build.

A similar fix has been added upstream with
https://github.com/brunoos/luasec/pull/30

Signed-off-by: Jo-Philipp Wich <jo@mein.io>