coreutils: update to 9.9
Release notes:
https://lists.gnu.org/archive/html/coreutils-announce/2025-09/msg00000.html
https://lists.gnu.org/archive/html/coreutils-announce/2025-11/msg00000.html

- Drop chcon and runcon as they require SELinux support and cannot be built from
  coreutils 9.9 when configured with --without-selinux.
- Add libgmp dependency for coreutils-basenc to fix missing libgmp.so.10.
- Switch to -std=gnu17 to avoid build failure.
  ```
  lib/openat-die.c: In function 'openat_save_fail':
  lib/openat-die.c:37:3: error: format not a string literal and no format arguments [-Werror=format-security]
     37 |   error (exit_failure, errnum,
        |   ^~~~~
  lib/openat-die.c: In function 'openat_restore_fail':
  lib/openat-die.c:56:3: error: format not a string literal and no format arguments [-Werror=format-security]
     56 |   error (exit_failure, errnum,
        |   ^~~~~
  ```
- Refresh patch.

Signed-off-by: Wei-Ting Yang <williamatcg@gmail.com>