Fix bug in git-daemon
The git-daemon command currently doesn't work and displays the following
error whenever a repository is cloned:

error: cannot run daemon: No such file or directory
[10920] unable to fork

On the client side the connection is simply terminated. The problem is,
that git-daemon tries to start a new instance of itself for every
new client that is connecting. It expects argv[0] to contain
"git-daemon", but since it is converted into a builtin command, argv[0]
only contains "daemon", which does not exist and causes the above error.
The fix simply prepends "git" to the list of arguments, so that the
resulting call looks something like "git daemon --serve ..."

Signed-off-by: Andreas Rohner <andreas.rohner@gmx.net>