qemu: Fix sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T
ERROR: sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.
       You probably need to set PKG_CONFIG_LIBDIR
       to point to the right pkg-config files for your
       build target

Signed-off-by: 李国 <uxgood.org@gmail.com>