openvswitch: don't build for kernel 4.14
Bulding OpenVSwitch currently fails for kernel 4.14. As 4.14 support is
set to be removed in the near future, don't build OpenVSwitch for kernel
4.14.

datapath/linux/geneve.c: In function 'geneve_get_v6_dst':
datapath/linux/geneve.c:966:17: error: 'const struct ipv6_stub' has no member
	named 'ipv6_dst_lookup'; did you mean 'ipv6_dst_lookup_flow'?
  if (ipv6_stub->ipv6_dst_lookup(geneve->net, gs6->sock->sk, &dst, fl6)) {
                 ^~~~~~~~~~~~~~~
                 ipv6_dst_lookup_flow

Signed-off-by: David Bauer <mail@david-bauer.net>