sslh: Also pass down TARGET_CPPFLAGS
Make sure we do pass TARGET_CPPFLAGS using CPPFLAGS (which is supported
by sslh's Makefile), fixing build issues with some external toolchains:

mipsel-linux-gnu-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc
-fno-caller-saves -Wno-unused-result  -D_FORTIFY_SOURCE=1 -Wl,-z,now
-Wl,-z,relro -DENABLE_REGEX -DLIBCONFIG -c sslh-main.c
sslh-main.c:26:23: fatal error: libconfig.h: No such file or directory
 #include <libconfig.h>
                       ^
compilation terminated.
Makefile:63: recipe for target 'sslh-main.o' failed
make[4]: *** [sslh-main.o] Error 1

Signed-off-by: Florian Fainelli <f.fainelli@gmail.com>