ustreamer: update to 6.52
fix a build error when compiled with WITH_SETPROCTITLE=1
undefined reference to setproctitle_init

[1] https://github.com/openwrt/packages/pull/28472#issuecomment-3863583824

Signed-off-by: Georgi Valkov <gvalkov@gmail.com>