host-pip-requirements: add Babel
One package (reforis-distutils [1]), which is not in this repo and it is required for Turris routers
because of reForis (simplified user interface), which is being developed
depends on Babel host package [2].

It fails with:
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/foo-omnia/build/feeds/packages/lang/python/host-pip-requirements/Babel.txt'

[1] https://gitlab.nic.cz/turris/turris-os-packages/-/blob/v5.1.4/web/reforis/reforis-distutils/Makefile#L23
[2] https://gitlab.nic.cz/turris/reforis/reforis-distutils/-/blob/v0.1.0/setup.py#L13

Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>