netbird: downgrade to version 0.17.0
The version, which is currently in OpenWrt 22.03 requires Go 1.20.

See the output:
../../../../../dl/go-mod-cache/github.com/netbirdio/wireguard-go@v0.0.0-20230524172305-5a498a82b33f/tun/tun_linux.go:362:18: undefined: errors.Join
note: module requires Go 1.20

Having Go 1.20 in OpenWrt 22.03 could be time consuming and as it is the stable branch, it seems like better idea to downgrade netbird to version 0.17.0, which is the latest version, which requires to use Go 1.19.

Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>