klish: Fix build errors with external toolchains
We would first not be able to properly detect libxml2 because it's not
automatically found, fix that by explicitly linking against it (and zlib
a dependency). Then if we don't don't define X_OPEN_SOURCE=500, we would
run into the following build error:

clish/shell/shell_execute.c: In function 'clish_shell_exec_action':
clish/shell/shell_execute.c:309:18: error: 'sigignore' undeclared (first
use in this function)
  sa.sa_handler = sigignore; /* Empty signal handler */
                  ^
clish/shell/shell_execute.c:309:18: note: each undeclared identifier is
reported only once for each function it appears in

Signed-off-by: Florian Fainelli <f.fainelli@gmail.com>