flashrom: update to v1.0
Update to flashrom version 1.0 and cherry-pick an upstream fix for deprecated
libusb api usage.

Fixes the following error spotted by the buildbots:

    ch341a_spi.c: In function 'ch341a_spi_init':
    ch341a_spi.c:447:2: error: 'libusb_set_debug' is deprecated: [...]
      libusb_set_debug(NULL, 3); // Enable information, warning and [...]
      ^~~~~~~~~~~~~~~~
    In file included from ch341a_spi.c:25:0:
    .../libusb-1.0/libusb.h:1300:18: note: declared here
     void LIBUSB_CALL libusb_set_debug(libusb_context *ctx, int level);
                      ^~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
    Makefile:1030: recipe for target 'ch341a_spi.o' failed

Signed-off-by: Jo-Philipp Wich <jo@mein.io>