dufs: lock cargo dependencies
The new version of tokio is not compatible with musl:

error[E0432]: unresolved import `tokio::net::TcpListener`
  --> src/main.rs:34:13
   |
34 | use tokio::{net::TcpListener, task::JoinHandle};
   |             ^^^^^^^^^^^^^^^^ no `TcpListener` in `net`

error[E0433]: failed to resolve: could not find `UnixListener` in `net`
   --> src/main.rs:156:44
    |
156 |                 let listener = tokio::net::UnixListener::bind(socket_path)
    |                                            ^^^^^^^^^^^^ could not find `UnixListener` in `net`

Signed-off-by: Tianling Shen <cnsztl@immortalwrt.org>
(cherry picked from commit 1716415018d67a4e0038639a87d7f484d73f89b1)