jool: remove dependency on kmod-nf-conntrack6
nf-conntrack_ipv6 is not longer a separate kernel module and was removed.
This prevents installation of jool.

```
ERROR: unable to select packages:
  kmod-nf-conntrack6 (no such package):
    required by: kmod-jool-netfilter-6.12.66.4.1.14-r3[kmod-nf-conntrack6]
```

Fixes: 5b61a50244ebc82096f5949de294ad69851e1fd6 ("netfilter: remove nf-conntrack6")
Signed-off-by: Goetz Goerisch <ggoerisch@gmail.com>