diffutils: fix 'compilation error on x86_64
Here was the first error I got:

  xstrtol-error.c:84:26: error: invalid use of undefined type 'struct
  rpl_option'

More information on this error here:
  https://www.mail-archive.com/clfs-support@lists.clfs.org/msg00297.html

I'm not sure if this is an issue in my build environment, but I believe
this is the proper fix because gzip and zile use the same option:

  ./utils/gzip/Makefile:	gl_cv_func_getopt_gnu=yes \
  ./utils/zile/Makefile:	gl_cv_func_getopt_gnu=yes \

This commit is mostly a reformat/sign-off of previous work by Dirk
Morris <dmorris@untangle.com>

Signed-off-by: Sébastien Delafond <sdelafond@gmail.com>