icecast: allow access to iconv
Since commit d18692c libxml2 (and by extension libxslt) is linked against
iconv. Now icecast needs access to iconv as well. Without it the build fails.

xslt.c: In function 'xsltSaveResultToString':
xslt.c:72:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if (result->children == NULL)
     ^~
xslt.c:75:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
  buf = xmlAllocOutputBuffer(NULL);
  ^~~
xslt.c:81:27: error: dereferencing pointer to incomplete type 'xmlBuf' {aka 'struct _xmlBuf'}
   *doc_txt_len = buf->conv->use;
                           ^~
make[6]: *** [Makefile:545: xslt.o] Error 1
make[6]: Leaving directory '/openwrt/build_dir/target-mips_24kc_musl/icecast-2.4.4/src'

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>