libinput: fix and optimize build
Buildbots are reporting the following build failure:

-snip-
  CCLD     test-build-linker
../src/.libs/libinput.so: undefined reference to `static_assert'
-snap-

Since this is the only call to static_assert within the library,
removing this assertion seems to be reasonable.

While at, speed up the build by not building tests and documentation.

Signed-off-by: Michael Heimpold <mhei@heimpold.de>