tvheadend: update libhdhomerun
Recently, silicondust (developers of hdhomerun) did some cleanup and
removed old versions for hdhomerun library.

```
WGET            http://download.silicondust.com/hdhomerun/libhdhomerun_20150826.tgz
http://download.silicondust.com/hdhomerun/libhdhomerun_20150826.tgz:
2021-10-26 05:15:14 ERROR 404: Not Found.
```

And because of that, it is not possible to compile tvheadend, it ends
with following error:

```
In file included from src/input/mpegts/tvhdhomerun/tvhdhomerun.c:25:0:
src/input/mpegts/tvhdhomerun/tvhdhomerun_private.h:27:10: fatal error: libhdhomerun/hdhomerun.h: No such file or directory
 #include <libhdhomerun/hdhomerun.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Let's fix it by updating libdhdhomerun to newer version.

Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>