minicom: remove PKG_FIXUP:autoreconf
The definition PKG_FIXUP=:autorenconf is no longer necessary. If this
option is not removed, I get the following compilation error warning.

configure.ac:125: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:126: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library

And the compilation stops with the following message.

./configure: line 6690: syntax error near unexpected token `external'
./configure: line 6690: `AM_GNU_GETTEXT(external)'

Removing the PKG_FIXUP solves this.

Signed-off-by: Florian Eckert <fe@dev.tdt.de>